CREATE table classroom(
id  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT CR_PK PRIMARY KEY,
name VARCHAR(45) NOT NULL,
UNIQUE (name));

CREATE table student(
id  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT ST_PK PRIMARY KEY,
name VARCHAR(45) NOT NULL,
age INTEGER,
classroom_id INTEGER,
CONSTRAINT CR_ST_FK FOREIGN KEY (classroom_id) REFERENCES classroom(id)
);
